name = "placegoose"
compatibility_date = "2024-11-15"

compatibility_flags = [ "nodejs_compat" ]

assets = { directory = "public" }

# Includes .md files in bundle: 
# https://developers.cloudflare.com/workers/wrangler/configuration/#bundling
rules = [
  { type = "Text", globs = ["**/*.md"], fallthrough = true }
]

# Custom domain mapping to point the worker to placegoose.fp.dev
routes = [
  { pattern = "placegoose.fp.dev", custom_domain = true }
]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "CACHE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "placegoose-d1"
# Update when connecting to a production db
database_id = "2047c000-8986-49c1-8ccc-91c8edaa6f97"
migrations_dir = "drizzle/migrations"

# [ai]
# binding = "AI"

[observability]
enabled = true
# head_sampling_rate = 1

# The rate limiting API is in open beta.
# https://www.npmjs.com/package/@hono-rate-limiter/cloudflare
[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
# An identifier you define, that is unique to your Cloudflare account.
# Must be an integer.
namespace_id = "6666"

# Limit: the number of tokens allowed within a given period in a single
# Cloudflare location
# Period: the duration of the period, in seconds. Must be either 10 or 60
simple = { limit = 100, period = 60 }
